#!/usr/bin/env bash
exec /usr/bin/g++ \
  -B/usr/libexec/gcc/x86_64-TencentOS-linux/12 \
  -B/usr/lib/gcc/x86_64-TencentOS-linux/12 \
  -L/usr/lib/gcc/x86_64-TencentOS-linux/12 \
  -L/usr/lib64 \
  "$@"
